SEED_DATA = [
    # Ontario - Toronto / Mississauga
    {
        "name": "Equinix TR1 - Toronto",
        "operator": "Equinix",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "151 Front St W, Toronto, ON",
        "latitude": 43.6466,
        "longitude": -79.3801,
        "size_category": "colocation",
        "floor_space_sqft": 120000,
        "power_mw": 18.0,
        "year_established": 1999,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/toronto-data-centers/tr1",
    },
    {
        "name": "Equinix TR2 - Toronto",
        "operator": "Equinix",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "45 Wellington St W, Toronto, ON",
        "latitude": 43.6510,
        "longitude": -79.3745,
        "size_category": "colocation",
        "floor_space_sqft": 95000,
        "power_mw": 14.0,
        "year_established": 2005,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/toronto-data-centers/tr2",
    },
    {
        "name": "Equinix TR3 - Toronto",
        "operator": "Equinix",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "65 Overlea Blvd, Toronto, ON",
        "latitude": 43.7089,
        "longitude": -79.3953,
        "size_category": "colocation",
        "floor_space_sqft": 145000,
        "power_mw": 22.0,
        "year_established": 2012,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2,PCI-DSS",
        "operator_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/toronto-data-centers/tr3",
    },
    {
        "name": "Equinix TR4 - Toronto",
        "operator": "Equinix",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "75 Overlea Blvd, Toronto, ON",
        "latitude": 43.7095,
        "longitude": -79.3960,
        "size_category": "colocation",
        "floor_space_sqft": 160000,
        "power_mw": 24.0,
        "year_established": 2014,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/toronto-data-centers/tr4",
    },
    {
        "name": "Equinix TR5 - Toronto",
        "operator": "Equinix",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "Overlea Blvd, Toronto, ON",
        "latitude": 43.7100,
        "longitude": -79.3965,
        "size_category": "colocation",
        "floor_space_sqft": 200000,
        "power_mw": 30.0,
        "year_established": 2019,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/toronto-data-centers/tr5",
    },
    {
        "name": "Cologix YYZ1 - Mississauga",
        "operator": "Cologix",
        "city": "Mississauga",
        "province": "ON",
        "province_full": "Ontario",
        "address": "1 Robert Speck Pkwy, Mississauga, ON",
        "latitude": 43.5890,
        "longitude": -79.6441,
        "size_category": "colocation",
        "floor_space_sqft": 85000,
        "power_mw": 12.0,
        "year_established": 2004,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.cologix.com/data-centers/toronto/yyz1",
    },
    {
        "name": "Cologix YYZ2 - Toronto East",
        "operator": "Cologix",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "905 King St W, Toronto, ON",
        "latitude": 43.7714,
        "longitude": -79.3099,
        "size_category": "colocation",
        "floor_space_sqft": 75000,
        "power_mw": 10.0,
        "year_established": 2010,
        "tier_rating": "II",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.cologix.com/data-centers/toronto/yyz2",
    },
    {
        "name": "DataBank YYZ1",
        "operator": "DataBank",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "Toronto, ON",
        "latitude": 43.6533,
        "longitude": -79.3832,
        "size_category": "colocation",
        "floor_space_sqft": 60000,
        "power_mw": 9.0,
        "year_established": 2013,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.databank.com",
    },
    {
        "name": "Iron Mountain YYZ",
        "operator": "Iron Mountain",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "Toronto, ON",
        "latitude": 43.6751,
        "longitude": -79.4055,
        "size_category": "colocation",
        "floor_space_sqft": 50000,
        "power_mw": 8.0,
        "year_established": 2011,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.ironmountain.com",
    },
    {
        "name": "Microsoft Azure Canada Central",
        "operator": "Microsoft",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "Toronto, ON",
        "latitude": 43.7000,
        "longitude": -79.4200,
        "size_category": "hyperscale",
        "floor_space_sqft": 1000000,
        "power_mw": 120.0,
        "year_established": 2016,
        "tier_rating": "IV",
        "certifications": "ISO27001,SOC2,PCI-DSS,HIPAA",
        "operator_url": "https://azure.microsoft.com/en-ca/global-infrastructure/canada",
    },
    {
        "name": "Bell Canada DC - Mississauga",
        "operator": "Bell Canada",
        "city": "Mississauga",
        "province": "ON",
        "province_full": "Ontario",
        "address": "Mississauga, ON",
        "latitude": 43.5897,
        "longitude": -79.6423,
        "size_category": "enterprise",
        "floor_space_sqft": 100000,
        "power_mw": 15.0,
        "year_established": 2000,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://business.bell.ca/enterprise/products/data-centres",
    },
    {
        "name": "Rogers 151 Front Street",
        "operator": "Rogers",
        "city": "Toronto",
        "province": "ON",
        "province_full": "Ontario",
        "address": "151 Front St W, Toronto, ON",
        "latitude": 43.6467,
        "longitude": -79.3820,
        "size_category": "enterprise",
        "floor_space_sqft": 110000,
        "power_mw": 16.0,
        "year_established": 1995,
        "tier_rating": "III",
        "certifications": "ISO27001",
        "operator_url": "https://www.rogers.com/business/data-centre",
    },
    # Ontario - Ottawa
    {
        "name": "Cologix OTT1 - Ottawa",
        "operator": "Cologix",
        "city": "Ottawa",
        "province": "ON",
        "province_full": "Ontario",
        "address": "180 Kent St, Ottawa, ON",
        "latitude": 45.4201,
        "longitude": -75.6919,
        "size_category": "colocation",
        "floor_space_sqft": 55000,
        "power_mw": 8.0,
        "year_established": 2007,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.cologix.com/data-centers/ottawa/ott1",
    },
    {
        "name": "Bell Canada DC - Ottawa",
        "operator": "Bell Canada",
        "city": "Ottawa",
        "province": "ON",
        "province_full": "Ontario",
        "address": "160 Elgin St, Ottawa, ON",
        "latitude": 45.4215,
        "longitude": -75.6900,
        "size_category": "enterprise",
        "floor_space_sqft": 70000,
        "power_mw": 10.0,
        "year_established": 2003,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://business.bell.ca/enterprise/products/data-centres",
    },
    # Quebec - Montreal
    {
        "name": "Cologix MTL1 - Montreal",
        "operator": "Cologix",
        "city": "Montreal",
        "province": "QC",
        "province_full": "Quebec",
        "address": "1 rue Holiday, Montreal, QC",
        "latitude": 45.5088,
        "longitude": -73.5540,
        "size_category": "colocation",
        "floor_space_sqft": 100000,
        "power_mw": 14.0,
        "year_established": 2006,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.cologix.com/data-centers/montreal/mtl1",
    },
    {
        "name": "Cologix MTL3 - Montreal",
        "operator": "Cologix",
        "city": "Montreal",
        "province": "QC",
        "province_full": "Quebec",
        "address": "8000 Decarie Blvd, Montreal, QC",
        "latitude": 45.5100,
        "longitude": -73.5550,
        "size_category": "colocation",
        "floor_space_sqft": 120000,
        "power_mw": 18.0,
        "year_established": 2018,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.cologix.com/data-centers/montreal/mtl3",
    },
    {
        "name": "Equinix ML1 - Montreal",
        "operator": "Equinix",
        "city": "Montreal",
        "province": "QC",
        "province_full": "Quebec",
        "address": "1350 Boul Rene-Levesque O, Montreal, QC",
        "latitude": 45.5017,
        "longitude": -73.5673,
        "size_category": "colocation",
        "floor_space_sqft": 90000,
        "power_mw": 13.0,
        "year_established": 2003,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/montreal-data-centers/ml1",
    },
    {
        "name": "Equinix ML2 - Montreal",
        "operator": "Equinix",
        "city": "Montreal",
        "province": "QC",
        "province_full": "Quebec",
        "address": "Montreal, QC",
        "latitude": 45.5020,
        "longitude": -73.5680,
        "size_category": "colocation",
        "floor_space_sqft": 110000,
        "power_mw": 16.0,
        "year_established": 2016,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2,PCI-DSS",
        "operator_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/montreal-data-centers/ml2",
    },
    {
        "name": "AWS Canada Central (ca-central-1)",
        "operator": "Amazon Web Services",
        "city": "Montreal",
        "province": "QC",
        "province_full": "Quebec",
        "address": "Montreal, QC",
        "latitude": 45.5236,
        "longitude": -73.5994,
        "size_category": "hyperscale",
        "floor_space_sqft": 800000,
        "power_mw": 100.0,
        "year_established": 2016,
        "tier_rating": "IV",
        "certifications": "ISO27001,SOC2,PCI-DSS,HIPAA,FedRAMP",
        "operator_url": "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/?p=ngi&loc=2",
    },
    {
        "name": "Google Cloud Montreal Region",
        "operator": "Google",
        "city": "Montreal",
        "province": "QC",
        "province_full": "Quebec",
        "address": "Montreal, QC",
        "latitude": 45.5080,
        "longitude": -73.5520,
        "size_category": "hyperscale",
        "floor_space_sqft": 600000,
        "power_mw": 80.0,
        "year_established": 2023,
        "tier_rating": "IV",
        "certifications": "ISO27001,SOC2,PCI-DSS",
        "operator_url": "https://cloud.google.com/about/locations/montreal",
    },
    {
        "name": "Digital Realty MTL1",
        "operator": "Digital Realty",
        "city": "Montreal",
        "province": "QC",
        "province_full": "Quebec",
        "address": "Montreal, QC",
        "latitude": 45.5230,
        "longitude": -73.5780,
        "size_category": "colocation",
        "floor_space_sqft": 140000,
        "power_mw": 20.0,
        "year_established": 2020,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.digitalrealty.com",
    },
    # Quebec - Other
    {
        "name": "QScale - Levis",
        "operator": "QScale",
        "city": "Levis",
        "province": "QC",
        "province_full": "Quebec",
        "address": "Levis, QC",
        "latitude": 46.8140,
        "longitude": -71.1759,
        "size_category": "hyperscale",
        "floor_space_sqft": 500000,
        "power_mw": 60.0,
        "year_established": 2022,
        "tier_rating": "III",
        "certifications": "ISO27001",
        "operator_url": "https://www.qscale.com",
    },
    {
        "name": "Bell Canada DC - Montreal",
        "operator": "Bell Canada",
        "city": "Montreal",
        "province": "QC",
        "province_full": "Quebec",
        "address": "Montreal, QC",
        "latitude": 45.4972,
        "longitude": -73.6139,
        "size_category": "enterprise",
        "floor_space_sqft": 95000,
        "power_mw": 14.0,
        "year_established": 2002,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://business.bell.ca/enterprise/products/data-centres",
    },
    # British Columbia - Vancouver
    {
        "name": "Equinix VAN1 - Vancouver",
        "operator": "Equinix",
        "city": "Vancouver",
        "province": "BC",
        "province_full": "British Columbia",
        "address": "555 W Hastings St, Vancouver, BC",
        "latitude": 49.2827,
        "longitude": -123.1207,
        "size_category": "colocation",
        "floor_space_sqft": 85000,
        "power_mw": 12.0,
        "year_established": 2007,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/vancouver-data-centers/va1",
    },
    {
        "name": "Equinix VAN2 - Vancouver",
        "operator": "Equinix",
        "city": "Vancouver",
        "province": "BC",
        "province_full": "British Columbia",
        "address": "Vancouver, BC",
        "latitude": 49.2831,
        "longitude": -123.1210,
        "size_category": "colocation",
        "floor_space_sqft": 100000,
        "power_mw": 15.0,
        "year_established": 2015,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/vancouver-data-centers/va2",
    },
    {
        "name": "Cologix VAN1 - Vancouver",
        "operator": "Cologix",
        "city": "Vancouver",
        "province": "BC",
        "province_full": "British Columbia",
        "address": "555 W Hastings St, Vancouver, BC",
        "latitude": 49.2760,
        "longitude": -123.1130,
        "size_category": "colocation",
        "floor_space_sqft": 70000,
        "power_mw": 10.0,
        "year_established": 2008,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.cologix.com/data-centers/vancouver/van1",
    },
    {
        "name": "TELUS Garden - Burnaby",
        "operator": "Telus",
        "city": "Burnaby",
        "province": "BC",
        "province_full": "British Columbia",
        "address": "4621 Canada Way, Burnaby, BC",
        "latitude": 49.2488,
        "longitude": -122.9805,
        "size_category": "enterprise",
        "floor_space_sqft": 120000,
        "power_mw": 18.0,
        "year_established": 2003,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.telus.com/en/business/data-centre",
    },
    {
        "name": "Shaw DC - Vancouver",
        "operator": "Shaw",
        "city": "Vancouver",
        "province": "BC",
        "province_full": "British Columbia",
        "address": "2055 Clark Dr, Vancouver, BC",
        "latitude": 49.2693,
        "longitude": -123.0802,
        "size_category": "enterprise",
        "floor_space_sqft": 80000,
        "power_mw": 11.0,
        "year_established": 2008,
        "tier_rating": "II",
        "certifications": "ISO27001",
        "operator_url": "https://www.shaw.ca/business",
    },
    # Alberta - Calgary
    {
        "name": "Cologix CAL1 - Calgary",
        "operator": "Cologix",
        "city": "Calgary",
        "province": "AB",
        "province_full": "Alberta",
        "address": "715 5 Ave SW, Calgary, AB",
        "latitude": 51.0447,
        "longitude": -114.0719,
        "size_category": "colocation",
        "floor_space_sqft": 65000,
        "power_mw": 9.0,
        "year_established": 2006,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.cologix.com/data-centers/calgary/cal1",
    },
    {
        "name": "Shaw DC - Calgary",
        "operator": "Shaw",
        "city": "Calgary",
        "province": "AB",
        "province_full": "Alberta",
        "address": "900 33 St NE, Calgary, AB",
        "latitude": 51.0720,
        "longitude": -113.9747,
        "size_category": "enterprise",
        "floor_space_sqft": 90000,
        "power_mw": 13.0,
        "year_established": 2006,
        "tier_rating": "II",
        "certifications": "ISO27001",
        "operator_url": "https://www.shaw.ca/business",
    },
    {
        "name": "TELUS DC - Calgary",
        "operator": "Telus",
        "city": "Calgary",
        "province": "AB",
        "province_full": "Alberta",
        "address": "411 1 St SE, Calgary, AB",
        "latitude": 51.0452,
        "longitude": -114.0570,
        "size_category": "enterprise",
        "floor_space_sqft": 95000,
        "power_mw": 14.0,
        "year_established": 2005,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.telus.com/en/business/data-centre",
    },
    # Alberta - Edmonton
    {
        "name": "TELUS DC - Edmonton",
        "operator": "Telus",
        "city": "Edmonton",
        "province": "AB",
        "province_full": "Alberta",
        "address": "10020 100 St NW, Edmonton, AB",
        "latitude": 53.5444,
        "longitude": -113.4909,
        "size_category": "enterprise",
        "floor_space_sqft": 85000,
        "power_mw": 12.0,
        "year_established": 2008,
        "tier_rating": "III",
        "certifications": "ISO27001,SOC2",
        "operator_url": "https://www.telus.com/en/business/data-centre",
    },
    {
        "name": "Shaw DC - Edmonton",
        "operator": "Shaw",
        "city": "Edmonton",
        "province": "AB",
        "province_full": "Alberta",
        "address": "630 Century St NW, Edmonton, AB",
        "latitude": 53.5688,
        "longitude": -113.5393,
        "size_category": "enterprise",
        "floor_space_sqft": 75000,
        "power_mw": 10.0,
        "year_established": 2010,
        "tier_rating": "II",
        "certifications": "ISO27001",
        "operator_url": "https://www.shaw.ca/business",
    },
    # Manitoba - Winnipeg
    {
        "name": "Bell MTS DC - Winnipeg",
        "operator": "Bell MTS",
        "city": "Winnipeg",
        "province": "MB",
        "province_full": "Manitoba",
        "address": "333 Main St, Winnipeg, MB",
        "latitude": 49.8954,
        "longitude": -97.1384,
        "size_category": "enterprise",
        "floor_space_sqft": 60000,
        "power_mw": 8.0,
        "year_established": 2005,
        "tier_rating": "II",
        "certifications": "ISO27001",
        "operator_url": "https://business.bell.ca/enterprise/products/data-centres",
    },
    # Nova Scotia - Halifax
    {
        "name": "Bell Aliant DC - Halifax",
        "operator": "Bell",
        "city": "Halifax",
        "province": "NS",
        "province_full": "Nova Scotia",
        "address": "1505 Barrington St, Halifax, NS",
        "latitude": 44.6476,
        "longitude": -63.5746,
        "size_category": "enterprise",
        "floor_space_sqft": 45000,
        "power_mw": 6.0,
        "year_established": 2006,
        "tier_rating": "II",
        "certifications": "ISO27001",
        "operator_url": "https://business.bell.ca/enterprise/products/data-centres",
    },
    # Saskatchewan - Regina
    {
        "name": "SaskTel DC - Regina",
        "operator": "SaskTel",
        "city": "Regina",
        "province": "SK",
        "province_full": "Saskatchewan",
        "address": "2121 Saskatchewan Dr, Regina, SK",
        "latitude": 50.4452,
        "longitude": -104.6189,
        "size_category": "enterprise",
        "floor_space_sqft": 50000,
        "power_mw": 7.0,
        "year_established": 2009,
        "tier_rating": "II",
        "certifications": "ISO27001",
        "operator_url": "https://www.sasktel.com/business",
    },
]


def seed_data(conn):
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM data_centres")
    if cursor.fetchone()[0] > 0:
        return
    cursor.executemany(
        """INSERT INTO data_centres
           (name, operator, city, province, province_full, address,
            latitude, longitude, size_category, floor_space_sqft, power_mw,
            year_established, tier_rating, certifications, operator_url)
           VALUES (:name, :operator, :city, :province, :province_full, :address,
                   :latitude, :longitude, :size_category, :floor_space_sqft, :power_mw,
                   :year_established, :tier_rating, :certifications, :operator_url)""",
        SEED_DATA,
    )
    conn.commit()
